### ISSUE TITLE
Editor can create chart using data retrieve from a table in the markdown

### ISSUE THREAD

**Issue by amoshydra** [nus-mtp/lecture-note-2.0#317]
Data like this:

Day| Apples | Oranges
---|---|---
M | 12 | 30
T | 19 | 29
W | 3 | 5
T | 17 | 5
F | 28 | 20
S | 24 | 3
S | 7 | 10

Can be converted into a chart like this

![](http://i.imgur.com/KoOxY3R.png)

## Todo:
- [ ] Webapp need to be able to extract data from a table
- [ ] Webapp need to be able to target specific table for rendering
- [ ] Webapp need to be able to embed and render chart using the given data
- [ ] Webapp need to be able to render a chart using the data from a table
